server:
  port: 28000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://8.136.8.92:3306/ra_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  mvc:
    static-path-pattern: classpath:/static/**
    view:
      prefix: classpath:/static/**
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html
    mode: HTML5
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
